menu:
 Home: /
 Resources: /resources
 Archive: /archives
#  RSS: /atom.xml

widgets:
 - greeting
 - site_links

rss: /atom.xml

readMore: ...read more

feed:
  type: atom
  path: atom.xml
  limit: 20
  hub:

tag_generator:
  per_page: 10
